services:
  postgresdb:
    image: postgres:16rc1-bullseye
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: bookwise
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "4455:5432"
